# Basic site settings
title: Fay Group
description: Fay Group @ UCLA website
baseurl: "" # Leave blank for GitHub Pages; otherwise, add "/your-repo-name"
url: "https://FayGroupUCLA.github.io" # Your GitHub Pages URL
# theme: minima
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: default

plugins:
- jekyll-include-cache
  # - jekyll-remote-theme
  
