remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

# Basic site settings
title: Fay Group
description: Fay Group @ UCLA website
baseurl: "" # Leave blank for GitHub Pages; otherwise, add "/your-repo-name"
url: "https://FayGroupUCLA.github.io" # Your GitHub Pages URL
# theme: minima

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
  
