# Basic site settings
title: Fay Group
description: Fay Group @ UCLA website
baseurl: "" # Leave blank for GitHub Pages; otherwise, add "/your-repo-name"
url: "https://FayGroupUCLA.github.io" # Your GitHub Pages URL
# theme: minima
markdown: kramdown
minimal_mistakes_skin: dark
skin: dark
remote_theme: "mmistakes/minimal-mistakes"


plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  # - jekyll-remote-theme
  
